# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
