# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170607_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_level',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='角色等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
