# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171212_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色')),
                ('role_level', models.CharField(blank=True, max_length=160, null=True, verbose_name='角色等级')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
    ]
