# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_finished',
            field=models.CharField(default=0, max_length=30, verbose_name='完成时间'),
        ),
    ]
