# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0002_script_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='is_finished',
            field=models.CharField(default=0, max_length=255, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.IntegerField(default=0, verbose_name='删除状态'),
        ),
    ]
