# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0004_auto_20180105_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='task_applyer_name',
            field=models.CharField(max_length=30, null=True, verbose_name='申请人'),
        ),
    ]
