# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0005_script_task_applyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='task_applyer_name',
        ),
        migrations.AlterField(
            model_name='script',
            name='is_finished',
            field=models.IntegerField(choices=[(0, 'unfinished'), (1, 'finished')], default=0, verbose_name='完成时间'),
        ),
    ]
