# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='%Y-%m-%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileSimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='upload/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_script', models.TextField(blank=True, null=True, verbose_name='脚本')),
                ('tool_run_type', models.IntegerField(choices=[(0, 'shell'), (1, 'python'), (2, 'sql')], default=0, verbose_name='脚本类型')),
                ('task_name', models.CharField(max_length=30, null=True, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=30, null=True, verbose_name='任务类型')),
                ('task_desc', models.CharField(max_length=256, null=True, verbose_name='任务描述')),
                ('task_applyer_name', models.CharField(max_length=30, null=True, verbose_name='申请人')),
                ('task_approve_name', models.CharField(max_length=30, null=True, verbose_name='审批人')),
                ('task_executer', models.CharField(max_length=30, null=True, verbose_name='执行人')),
                ('apply_time', models.CharField(max_length=30, null=True, verbose_name='提交时间')),
                ('finish_time', models.CharField(max_length=30, null=True, verbose_name='完成时间')),
                ('is_finished', models.CharField(max_length=30, null=True, verbose_name='完成时间')),
                ('task_script_path', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='脚本路径')),
            ],
            options={
                'verbose_name': '任务中心',
                'verbose_name_plural': '任务中心',
            },
        ),
    ]
