# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, null=True, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=30, null=True, verbose_name='任务类型')),
                ('task_desc', models.CharField(max_length=100, null=True, verbose_name='任务描述')),
                ('task_applyer_name', models.CharField(max_length=30, null=True, verbose_name='申请人')),
                ('task_approve_name', models.CharField(max_length=30, null=True, verbose_name='审批人')),
                ('task_executer', models.CharField(max_length=30, null=True, verbose_name='执行人')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP范围')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='接入带宽')),
            ],
            options={
                'verbose_name': '任务中心',
                'verbose_name_plural': '任务中心',
            },
        ),
    ]
