# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ip_range',
        ),
    ]
