# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171204_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_finshed',
            field=models.CharField(max_length=30, null=True, verbose_name='完成时间'),
        ),
    ]
