# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20171206_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_script_path',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='脚本路径'),
        ),
    ]
