# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_script_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tool_run_type',
            field=models.IntegerField(choices=[(0, 'shell'), (1, 'python'), (2, 'sql')], default=0, verbose_name='脚本类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='tool_script',
            field=models.TextField(blank=True, null=True, verbose_name='脚本'),
        ),
    ]
