# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='upload/%Y-%m-%d')),
            ],
        ),
    ]
